baseurl = "/"
languageCode = "en-us"
title = "Liam Michel Photography"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "My Photography Portfolio"
  cover = "images/cover.jpg"
  author = "Liam Michel"
  authorlocation = "Meadville, PA"
  authorwebsite = "http://vjeantet.fr"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  
  githubName = "liammichel"
  linkedinName = "liam-michel-1a15ba140"
  instagramName = "liammichel_photography"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
